name: Keep Codespace Alive

on:
  schedule:
    - cron: '0 */5 * * *' # Runs every 5 minutes

jobs:
  keep_alive:
    runs-on: ubuntu-latest

    steps:
      - name: Send request to Codespace
        run: |
          curl -s -o /dev/null https://your-codespace-name-namespace.devcontainers.codespaces.githubusercontent.com
